 export const specialties = [
    'Pediatrics',
    'Cardiologist',
    'Dermatology',
    'Endocrinologist',
    'Gastroenterologist',
    'Oncologist',
    'Family medicine',
    'Neurologist',
    'Psychiatrist',
    'Obstetrics and gynaecology',
    'Ophthalmology',
    'Radiology',
    'Anesthesiology',
    'Internal medicine',
    'Nephrologist',
    'ENT',
    'Immunology',
    'Geriatrics',
    'Hematology',
    'Infectious Disease Specialist',
    'Pulmonologist',
    'Urology',
    'Emergency medicine',
    'Orthopaedist',
  ];